"""Document intake: hashing, safety checks, and source-type/format detection.

Corresponds to DOC-001..DOC-005 in docs/invoice_phase1/control_catalog.md and
the "Intake"/"Safety checks"/"Format detection" rows of
docs/invoice_phase1/automation_boundary.md.

This module never raises for content the pipeline is designed to classify
(encrypted, unreadable-but-recognized, unknown structured format) -- those
become DOC-001/detectedFormat findings in the control report (HTTP 200). It
raises UnsupportedInputError for request-level rejections that never reach
the classification pipeline: bytes that aren't recognizable as a PDF or XML
at all (415), or a file/embedded-XML payload over the size limit (413).

Hardening notes (untrusted input from an external sender):
- All XML parsing here uses a locked-down lxml parser: no entity resolution
  (blocks internal-entity "billion laughs" expansion), no network access
  (blocks external-entity/XXE exfiltration and SSRF), no DTD loading.
- Only embedded PDF attachments using the well-known Factur-X/ZUGFeRD/
  Order-X filenames are extracted (via facturx.get_xml_from_pdf). Earlier
  drafts of this module also fell back to extracting *any* embedded file
  that merely looked like XML by filename heuristic
  (facturx.extract_any_xml_from_pdf) -- that fallback let an attacker embed
  and have this service parse an arbitrary attached XML file. It is
  intentionally not used on this path. The legacy `/facturx-pdfextractxml`
  endpoint still offers that behavior, but only as an explicit
  `accept_any_filename=True` opt-in on a request-by-request basis, not a
  default.
"""
import hashlib
from dataclasses import dataclass, field
from io import BytesIO
from typing import Optional

from lxml import etree
from pypdf import PdfReader
from pypdf.errors import PdfReadError

from ..facturx import ALL_FILENAMES, get_flavor, get_level, get_xml_from_pdf
from .errors import UnsupportedInputError

MAX_UPLOAD_BYTES = 20 * 1024 * 1024  # 20 MiB
MAX_EMBEDDED_XML_BYTES = 5 * 1024 * 1024  # 5 MiB

# The factur-x library's own ALL_FILENAMES is hyphenated only
# (factur-x.xml, zugferd-invoice.xml, ZUGFeRD-invoice.xml, order-x.xml) --
# confirmed against a real Unternehmen X invoice (a real supplier's
# invoice generated by Microsoft SSRS/PDFsharp) that embeds its XML as
# "ZUGFeRD_Invoice.xml"
# (underscore, different capitalization), which the exact-match check
# silently missed -- inspect_document reported plain "pdf" with zero
# warnings even though a real, valid CrossIndustryInvoice XML was sitting
# right there in the PDF's embedded files. This is a curated ADDITION, not
# a switch to accept-any-filename: still a small, human-reviewed exact-match
# list (the security property the module docstring describes), just one
# real-world vendor convention wider.
_REAL_WORLD_EMBEDDED_XML_FILENAMES = ALL_FILENAMES + ["ZUGFeRD_Invoice.xml"]

# resolve_entities=False blocks internal general-entity expansion (the
# "billion laughs" DoS pattern) independent of network access.
# no_network=True additionally blocks fetching *external* entities/DTDs
# (XXE file/SSRF exfiltration). load_dtd=False skips DTD processing
# entirely. huge_tree=False (lxml's default, set explicitly here for
# clarity) caps overall tree size/depth.
_SECURE_XML_PARSER = etree.XMLParser(
    resolve_entities=False,
    no_network=True,
    dtd_validation=False,
    load_dtd=False,
    huge_tree=False,
)


@dataclass
class DocumentInspection:
    source_type: str  # hybrid_pdf | plain_pdf | xml
    filename: str
    mime_type: str
    sha256: str
    detected_format: str  # factur-x | xrechnung | pdf | unknown
    format_version: Optional[str] = None
    profile: Optional[str] = None
    readable: bool = True
    encrypted: bool = False
    embedded_xml_bytes: Optional[bytes] = None
    xml_bytes: Optional[bytes] = None
    xml_etree: Optional[etree._Element] = None
    warnings: list[str] = field(default_factory=list)


# Validated 2026-09-03/04 across multiple random-sample accuracy rounds
# against a real pilot organization's invoices (see the n8n Flow 1b
# "text-extraction-first" lane, examples/n8n/digitax_invoice_phase1_flow1b_pdf_ocr_concept_v0_3_0.json):
# most real invoices are born-digital PDFs with a fully extractable, lossless
# text layer, and 50 characters is enough to separate that from a near-empty
# layer (a scanned PDF with only a handful of stray characters from a
# corrupted/partial embedded OCR layer, or none at all). This is the exact
# threshold POST /v1/invoices/extract-text already validated and exposed to
# that n8n workflow -- reused here verbatim, not re-derived, so both callers
# agree on what counts as "usable".
MIN_REAL_TEXT_CHARS = 50


@dataclass
class TextLayerInspection:
    text: str
    char_count: int
    has_text: bool  # True: usable/meaningful embedded text (digitally-born).
    # False: empty, whitespace-only, or too thin to be meaningful (e.g. a
    # scanned image with no OCR text layer, or only a corrupted stray-
    # character remnant of one) -- this PDF needs OCR/vision extraction.


def inspect_text_layer(file_bytes: bytes) -> TextLayerInspection:
    """Determines whether a plain PDF has a usable embedded text layer.

    "Usable" is deliberately a low bar (>= MIN_REAL_TEXT_CHARS of non-
    whitespace extracted text, no further quality/language/garbage check):
    a real digitally-born invoice reliably clears it by a wide margin (real
    invoices carry far more than 50 characters of header/party/total text),
    while a genuine scan with no text layer at all reliably extracts to ""
    -- pypdf's extract_text() only reads real text-showing operators from
    the content stream, never OCRs image content, so there is no ambiguous
    middle ground to tune against in practice. A PDF this can't even open
    (corrupt/encrypted) is treated as "no usable text" rather than raising --
    the caller (pipeline.py) only ever reaches this for a PDF DOC-001 has
    already accepted as readable/unencrypted, but this function is also
    used by the standalone POST /v1/invoices/extract-text endpoint against
    arbitrary caller input, so it must degrade gracefully on its own.
    """
    try:
        reader = PdfReader(BytesIO(file_bytes))
        text = "".join(page.extract_text() or "" for page in reader.pages)
    except Exception:
        text = ""
    return TextLayerInspection(
        text=text,
        char_count=len(text),
        has_text=len(text.strip()) >= MIN_REAL_TEXT_CHARS,
    )


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _looks_like_xml(data: bytes) -> bool:
    stripped = data.lstrip(b"\xef\xbb\xbf \t\r\n")
    return stripped.startswith(b"<?xml") or stripped.startswith(b"<")


def _parse_untrusted_xml(xml_bytes: bytes) -> etree._Element:
    """The only place raw untrusted XML bytes are turned into an lxml tree
    on this path. Always goes through _SECURE_XML_PARSER."""
    return etree.fromstring(xml_bytes, parser=_SECURE_XML_PARSER)


def _detect_structured_format(xml_bytes: bytes, warnings: list[str]) -> tuple:
    """Returns (detected_format, format_version, profile, xml_etree) for XML bytes.

    format_version is always None here, deliberately: Factur-X does not
    reliably encode its own document release (e.g. 1.07.2 vs 1.09) in
    content we can detect -- the Guideline ID only encodes the PROFILE
    (minimum/basicwl/basic/en16931/extended), not a release number. Do not
    conflate that with the XSD/validator baseline this service actually
    checks against, which is a property of the service, not the document,
    and is already exposed via STR-003's ruleVersion and
    /capabilities.structuredFormats["factur-x"].xsdVersion.
    """
    try:
        xml_etree = _parse_untrusted_xml(xml_bytes)
    except Exception as exc:
        warnings.append(f"XML_NOT_WELL_FORMED_OR_REJECTED: {exc}")
        return "unknown", None, None, None
    if _is_xrechnung(xml_etree):
        # Same CrossIndustryInvoice root tag as Factur-X, but the Guideline
        # ID identifies the German XRechnung CIUS specifically. Must be
        # checked before falling through to the generic Factur-X flavor
        # detection below, which only looks at the root tag name and would
        # otherwise misclassify it as factur-x.
        warnings.append("DETECTED_XRECHNUNG_GUIDELINE_ID")
        return "xrechnung", None, None, xml_etree
    try:
        flavor = get_flavor(xml_etree)
    except Exception as exc:
        warnings.append(f"UNRECOGNIZED_XML_FLAVOR: {exc}")
        return "unknown", None, None, xml_etree
    if flavor not in ("factur-x", "facturx"):
        # zugferd 1.0 / order-x are out of scope for the invoice control profile
        warnings.append(f"UNSUPPORTED_XML_FLAVOR: {flavor}")
        return "unknown", None, None, xml_etree
    try:
        level = get_level(xml_etree, flavor="factur-x")
    except Exception as exc:
        warnings.append(f"UNRECOGNIZED_PROFILE_LEVEL: {exc}")
        return "factur-x", None, None, xml_etree
    return "factur-x", None, level.upper(), xml_etree


_XRECHNUNG_GUIDELINE_ID_PATH = (
    "//rsm:ExchangedDocumentContext"
    "/ram:GuidelineSpecifiedDocumentContextParameter/ram:ID"
)
_XRECHNUNG_GUIDELINE_MARKERS = ("xrechnung", "kosit")


def _is_xrechnung(xml_etree: etree._Element) -> bool:
    from ..facturx import XML_NAMESPACES

    try:
        matches = xml_etree.xpath(
            _XRECHNUNG_GUIDELINE_ID_PATH, namespaces=XML_NAMESPACES["factur-x"]
        )
    except Exception:
        return False
    guideline_id = (matches[0].text or "").strip().lower() if matches else ""
    return any(marker in guideline_id for marker in _XRECHNUNG_GUIDELINE_MARKERS)


def inspect_document(
    file_bytes: bytes, filename: str, content_type: str
) -> DocumentInspection:
    if not file_bytes:
        raise UnsupportedInputError(
            "EMPTY_FILE", "The uploaded file is empty.", status_code=400
        )
    if len(file_bytes) > MAX_UPLOAD_BYTES:
        raise UnsupportedInputError(
            "FILE_TOO_LARGE",
            f"The uploaded file exceeds the {MAX_UPLOAD_BYTES} byte limit.",
            status_code=413,
        )

    sha256 = _sha256(file_bytes)
    warnings: list[str] = []

    if file_bytes.startswith(b"%PDF"):
        return _inspect_pdf(file_bytes, filename, content_type, sha256, warnings)
    if _looks_like_xml(file_bytes):
        detected_format, format_version, profile, xml_etree = (
            _detect_structured_format(file_bytes, warnings)
        )
        return DocumentInspection(
            source_type="xml",
            filename=filename,
            mime_type=content_type or "application/xml",
            sha256=sha256,
            detected_format=detected_format,
            format_version=format_version,
            profile=profile,
            readable=True,
            encrypted=False,
            xml_bytes=file_bytes,
            xml_etree=xml_etree,
            warnings=warnings,
        )

    raise UnsupportedInputError(
        "UNSUPPORTED_CONTENT_TYPE",
        "The uploaded file is neither a recognizable PDF nor a recognizable "
        "XML document.",
        status_code=415,
    )


def _inspect_pdf(
    file_bytes: bytes,
    filename: str,
    content_type: str,
    sha256: str,
    warnings: list[str],
) -> DocumentInspection:
    readable = True
    encrypted = False
    try:
        reader = PdfReader(BytesIO(file_bytes))
        encrypted = bool(reader.is_encrypted)
        if not encrypted:
            # touch page count to force a basic structural read
            _ = len(reader.pages)
    except PdfReadError as exc:
        readable = False
        warnings.append(f"PDF_UNREADABLE: {exc}")
    except Exception as exc:
        readable = False
        warnings.append(f"PDF_UNREADABLE: {exc}")

    if not readable or encrypted:
        return DocumentInspection(
            source_type="plain_pdf",
            filename=filename,
            mime_type=content_type or "application/pdf",
            sha256=sha256,
            detected_format="pdf",
            readable=readable,
            encrypted=encrypted,
            warnings=warnings,
        )

    embedded_xml_bytes = None
    try:
        # Only well-known Factur-X/ZUGFeRD/Order-X attachment filenames are
        # accepted -- see module docstring. No arbitrary-embedded-file
        # fallback on this path. _REAL_WORLD_EMBEDDED_XML_FILENAMES extends
        # the library's own hyphenated-only default with one confirmed
        # real-world vendor variant (see its own definition above).
        _, embedded_xml_bytes = get_xml_from_pdf(
            BytesIO(file_bytes),
            check_xsd=False,
            filenames=_REAL_WORLD_EMBEDDED_XML_FILENAMES,
        )
    except Exception as exc:
        warnings.append(f"EMBEDDED_XML_EXTRACTION_FAILED: {exc}")
        embedded_xml_bytes = None

    if embedded_xml_bytes and len(embedded_xml_bytes) > MAX_EMBEDDED_XML_BYTES:
        # This is a known structured invoice (a well-known Factur-X/ZUGFeRD/
        # Order-X attachment name was found) that we can't safely process --
        # NOT the same fact as "this PDF never had structured data at all".
        # Downgrading it to plain_pdf would let it flow through the PDF/OCR
        # mock-adapter path and potentially produce a false unauffaellig/
        # passing verdict for a document whose actual structured content was
        # never examined. detected_format="unknown" keeps source_type as
        # hybrid_pdf and fails DOC-001 (format_supported check in
        # pipeline.py), routing to nicht_pruefbar instead.
        warnings.append(
            f"EMBEDDED_XML_TOO_LARGE: {len(embedded_xml_bytes)} bytes "
            f"exceeds the {MAX_EMBEDDED_XML_BYTES} byte limit; not processed"
        )
        return DocumentInspection(
            source_type="hybrid_pdf",
            filename=filename,
            mime_type=content_type or "application/pdf",
            sha256=sha256,
            detected_format="unknown",
            readable=True,
            encrypted=False,
            warnings=warnings,
        )

    if embedded_xml_bytes:
        detected_format, format_version, profile, xml_etree = (
            _detect_structured_format(embedded_xml_bytes, warnings)
        )
        return DocumentInspection(
            source_type="hybrid_pdf",
            filename=filename,
            mime_type=content_type or "application/pdf",
            sha256=sha256,
            detected_format=detected_format,
            format_version=format_version,
            profile=profile,
            readable=True,
            encrypted=False,
            embedded_xml_bytes=embedded_xml_bytes,
            xml_bytes=embedded_xml_bytes,
            xml_etree=xml_etree,
            warnings=warnings,
        )

    return DocumentInspection(
        source_type="plain_pdf",
        filename=filename,
        mime_type=content_type or "application/pdf",
        sha256=sha256,
        detected_format="pdf",
        readable=True,
        encrypted=False,
        warnings=warnings,
    )
